using FluxifyAPI.Data;
using FluxifyAPI.DTOs.Product;
using FluxifyAPI.DTOs.ProductSku;
using FluxifyAPI.Helpers;
using FluxifyAPI.Mapper;
using FluxifyAPI.Models;
using FluxifyAPI.Repository.Interfaces;
using FluxifyAPI.Services.Common;
using FluxifyAPI.Services.Interfaces;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;

namespace FluxifyAPI.Services.Implementations
{
    public class ProductService : IProductService
    {
        private const int MaxAutoGeneratedSkuCount = 500;

        private sealed class ProductCreationData
        {
            public Dictionary<string, List<string>>? Attributes { get; init; }
            public List<CreateProductSkuRequestDto> Skus { get; init; } = new();
        }

        private readonly AppDbContext _context;
        private readonly IProductRepository _productRepository;
        private readonly IProductSkuRepository _productSkuRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly ITenantRepository _tenantRepository;
        private readonly ICartItemRepository _cartItemRepository;
        private readonly IReviewRepository _reviewRepository;
        private readonly IOrderItemRepository _orderItemRepository;

        public ProductService(
            AppDbContext context,
            IProductRepository productRepository,
            IProductSkuRepository productSkuRepository,
            ICategoryRepository categoryRepository,
            ITenantRepository tenantRepository,
            ICartItemRepository cartItemRepository,
            IReviewRepository reviewRepository,
            IOrderItemRepository orderItemRepository)
        {
            _context = context;
            _productRepository = productRepository;
            _productSkuRepository = productSkuRepository;
            _categoryRepository = categoryRepository;
            _tenantRepository = tenantRepository;
            _cartItemRepository = cartItemRepository;
            _reviewRepository = reviewRepository;
            _orderItemRepository = orderItemRepository;
        }

        private static Dictionary<string, List<string>>? NormalizeProductAttributes(Dictionary<string, List<string>>? attributes)
        {
            if (attributes == null || attributes.Count == 0)
                return null;

            var normalized = new Dictionary<string, List<string>>(StringComparer.OrdinalIgnoreCase);

            foreach (var entry in attributes)
            {
                if (string.IsNullOrWhiteSpace(entry.Key))
                    continue;

                var normalizedKey = entry.Key.Trim();
                var normalizedValues = (entry.Value ?? new List<string>())
                    .Where(v => !string.IsNullOrWhiteSpace(v))
                    .Select(v => v.Trim())
                    .Distinct(StringComparer.OrdinalIgnoreCase)
                    .ToList();

                normalized[normalizedKey] = normalizedValues;
            }

            return normalized.Count == 0 ? null : normalized;
        }

        private static Dictionary<string, string> NormalizeSkuAttributes(Dictionary<string, string>? attributes)
        {
            if (attributes == null || attributes.Count == 0)
                return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

            var normalized = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            foreach (var entry in attributes)
            {
                if (string.IsNullOrWhiteSpace(entry.Key) || string.IsNullOrWhiteSpace(entry.Value))
                    continue;

                normalized[entry.Key.Trim()] = entry.Value.Trim();
            }

            return normalized;
        }

        private static string BuildSkuAttributeKey(IReadOnlyDictionary<string, string> attributes)
        {
            return string.Join("|", attributes
                .OrderBy(entry => entry.Key, StringComparer.OrdinalIgnoreCase)
                .Select(entry => $"{entry.Key.ToLowerInvariant()}={entry.Value.ToLowerInvariant()}"));
        }

        private static List<Dictionary<string, string>> BuildAttributeCombinations(Dictionary<string, List<string>> productAttributes)
        {
            var combinations = new List<Dictionary<string, string>>
            {
                new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            };

            foreach (var attributeGroup in productAttributes)
            {
                var nextCombinations = new List<Dictionary<string, string>>();
                foreach (var existingCombination in combinations)
                    foreach (var value in attributeGroup.Value)
                    {
                        var nextCombination = new Dictionary<string, string>(existingCombination, StringComparer.OrdinalIgnoreCase)
                        {
                            [attributeGroup.Key] = value
                        };

                        nextCombinations.Add(nextCombination);
                    }
                combinations = nextCombinations;
            }
            return combinations;
        }

        private static ServiceResult<ProductCreationData> ResolveProductCreationData(CreateProductRequestDto createDto)
        {
            var normalizedProductAttributes = NormalizeProductAttributes(createDto.Attributes);
            if (normalizedProductAttributes == null)
            {
                return ServiceResult<ProductCreationData>.Ok(new ProductCreationData
                {
                    Attributes = null,
                    Skus = createDto.Skus ?? new List<CreateProductSkuRequestDto>()
                });
            }
            if (normalizedProductAttributes.Any(attribute => attribute.Value.Count == 0))
                return ServiceResult<ProductCreationData>.Fail(400, "Mỗi nhóm thuộc tính phải có ít nhất một giá trị");
            long skuCount = 1;
            foreach (var values in normalizedProductAttributes.Values)
            {
                skuCount *= values.Count;
                if (skuCount > MaxAutoGeneratedSkuCount)
                    return ServiceResult<ProductCreationData>.Fail(400, $"Số lượng SKU tự động vượt quá giới hạn {MaxAutoGeneratedSkuCount}");
            }

            var providedSkus = createDto.Skus ?? new List<CreateProductSkuRequestDto>();
            var providedSkuByKey = new Dictionary<string, CreateProductSkuRequestDto>(StringComparer.OrdinalIgnoreCase);
            CreateProductSkuRequestDto? defaultSkuTemplate = null;

            foreach (var providedSku in providedSkus)
            {
                var normalizedSkuAttributes = NormalizeSkuAttributes(providedSku.Attributes);
                if (normalizedSkuAttributes.Count == 0)
                {
                    defaultSkuTemplate ??= providedSku;
                    continue;
                }

                foreach (var skuAttribute in normalizedSkuAttributes)
                {
                    if (!normalizedProductAttributes.TryGetValue(skuAttribute.Key, out var allowedValues) ||
                        !allowedValues.Contains(skuAttribute.Value, StringComparer.OrdinalIgnoreCase))
                    {
                        return ServiceResult<ProductCreationData>.Fail(
                            400,
                            $"SKU attributes không hợp lệ: {skuAttribute.Key}={skuAttribute.Value}");
                    }
                }

                var skuKey = BuildSkuAttributeKey(normalizedSkuAttributes);
                if (!providedSkuByKey.TryAdd(skuKey, providedSku))
                    return ServiceResult<ProductCreationData>.Fail(400, "Có SKU bị trùng tổ hợp attributes");
            }

            var combinations = BuildAttributeCombinations(normalizedProductAttributes);
            var autoGeneratedSkus = new List<CreateProductSkuRequestDto>(combinations.Count);

            foreach (var combination in combinations)
            {
                var combinationKey = BuildSkuAttributeKey(combination);

                if (providedSkuByKey.TryGetValue(combinationKey, out var providedSku))
                {
                    autoGeneratedSkus.Add(new CreateProductSkuRequestDto
                    {
                        Price = providedSku.Price,
                        Stock = providedSku.Stock,
                        ImgUrl = providedSku.ImgUrl,
                        Attributes = combination
                    });
                    continue;
                }

                if (defaultSkuTemplate != null)
                {
                    autoGeneratedSkus.Add(new CreateProductSkuRequestDto
                    {
                        Price = defaultSkuTemplate.Price,
                        Stock = defaultSkuTemplate.Stock,
                        ImgUrl = defaultSkuTemplate.ImgUrl,
                        Attributes = combination
                    });
                    continue;
                }

                return ServiceResult<ProductCreationData>.Fail(
                    400,
                    "Thiếu thông tin SKU cho một hoặc nhiều tổ hợp thuộc tính. Hãy cung cấp đầy đủ SKU hoặc một SKU mặc định để sao chép price/stock/imgUrl.");
            }

            return ServiceResult<ProductCreationData>.Ok(new ProductCreationData
            {
                Attributes = normalizedProductAttributes,
                Skus = autoGeneratedSkus
            });
        }

        private async Task<ServiceResult<object>> RemoveProductSkusAsync(Guid tenantId, IEnumerable<ProductSku> skus)
        {
            var skuIdList = skus?.Select(sku => sku.Id).Distinct().ToList() ?? new List<Guid>();
            if (skuIdList.Count == 0)
                return ServiceResult<object>.Ok(new { message = "Không có SKU cần xóa" });

            if (await _orderItemRepository.HasOrderItemsByProductSkusAsync(tenantId, skuIdList))
                return ServiceResult<object>.Fail(400, "Không thể xóa SKU vì đang được tham chiếu trong đơn hàng");

            var hasReviews = await _context.Reviews
                .AsNoTracking()
                .AnyAsync(review => review.TenantId == tenantId && skuIdList.Contains(review.ProductSkuId));
            if (hasReviews)
                return ServiceResult<object>.Fail(400, "Không thể xóa SKU vì đang có review. Hãy archive/unpublish SKU thay vì xóa vật lý.");

            foreach (var skuId in skuIdList)
            {
                await _cartItemRepository.DeleteCartItemsByProductSkuAsync(tenantId, skuId);
                await _productSkuRepository.DeleteProductSkuAsync(tenantId, skuId);
            }

            return ServiceResult<object>.Ok(new { message = "Đã xóa SKU không còn tham chiếu đơn hàng/review" });
        }

        public async Task<ServiceResult<IEnumerable<ProductDto>>> GetProductsAsync(Guid tenantId, QueryProduct query)
        {
            var productQuery = _productRepository.GetProductsByTenant(tenantId);

            var searchTerm = query.SearchTerm;
            if (!string.IsNullOrEmpty(searchTerm))
                productQuery = productQuery
                    .Where(p => p.Name.Contains(searchTerm) || (p.Description != null && p.Description.Contains(searchTerm)));
            if (!string.IsNullOrWhiteSpace(query.Name))
                productQuery = productQuery.Where(p => p.Name.Contains(query.Name.Trim()));
            if (query.CategoryId.HasValue)
                productQuery = productQuery.Where(p => p.CategoryId == query.CategoryId.Value);
            if (query.HasAttributes.HasValue)
                productQuery = query.HasAttributes.Value
                    ? productQuery.Where(p => !string.IsNullOrEmpty(p.AttributesJson))
                    : productQuery.Where(p => string.IsNullOrEmpty(p.AttributesJson));
            if (query.PriceFrom.HasValue && query.PriceFrom.Value < 0)
                return ServiceResult<IEnumerable<ProductDto>>.Fail(400, "PriceFrom phải lớn hơn hoặc bằng 0");
            if (query.PriceTo.HasValue && query.PriceTo.Value < 0)
                return ServiceResult<IEnumerable<ProductDto>>.Fail(400, "PriceTo phải lớn hơn hoặc bằng 0");
            if (query.PriceFrom.HasValue && query.PriceTo.HasValue && query.PriceTo.Value < query.PriceFrom.Value)
                return ServiceResult<IEnumerable<ProductDto>>.Fail(400, "PriceTo phải lớn hơn hoặc bằng PriceFrom");
            if (query.PriceFrom.HasValue)
                productQuery = productQuery.Where(p => p.ProductSkus.Any(sku => sku.Price >= query.PriceFrom.Value));
            if (query.PriceTo.HasValue)
                productQuery = productQuery.Where(p => p.ProductSkus.Any(sku => sku.Price <= query.PriceTo.Value));
            var isDescending = string.Equals(query.SortDirection, "desc", StringComparison.OrdinalIgnoreCase);
            switch (query.SortBy)
            {
                case "name":
                    productQuery = isDescending ? productQuery.OrderByDescending(p => p.Name) : productQuery.OrderBy(p => p.Name);
                    break;
                case "categoryid":
                case "category_id":
                    productQuery = isDescending ? productQuery.OrderByDescending(p => p.CategoryId) : productQuery.OrderBy(p => p.CategoryId);
                    break;
                case "id":
                    productQuery = isDescending ? productQuery.OrderByDescending(p => p.Id) : productQuery.OrderBy(p => p.Id);
                    break;
                default:
                    productQuery = productQuery.OrderBy(p => p.Id);
                    break;
            }
            var skipNumber = (query.Page - 1) * query.PageSize;
            var products = await productQuery.Skip(skipNumber).Take(query.PageSize).ToListAsync();
            return ServiceResult<IEnumerable<ProductDto>>.Ok(products.Select(p => p.ToProductDto()));
        }

        public async Task<ServiceResult<ProductDetailDto>> GetProductDetailAsync(Guid tenantId, Guid id)
        {
            var product = await _productRepository.GetProductAsync(tenantId, id);
            if (product == null)
                return ServiceResult<ProductDetailDto>.Fail(404, "Không tìm thấy sản phẩm");

            return ServiceResult<ProductDetailDto>.Ok(product.ToProductDetailDto());
        }
        public async Task<ServiceResult<ProductDto>> GetProductAsync(Guid tenantId, Guid id)
        {
            var product = await _productRepository.GetProductAsync(tenantId, id);
            if (!await _productRepository.ProductExists(tenantId, id) || product == null)
                return ServiceResult<ProductDto>.Fail(404, "Không tìm thấy sản phẩm");
            return ServiceResult<ProductDto>.Ok(product.ToProductDto());
        }

        public async Task<ServiceResult<ProductDto>> CreateProductAsync(Guid tenantId, Guid platformUserId, CreateProductRequestDto createDto)
        {
            if (!await _tenantRepository.IsTenantOwner(tenantId, platformUserId))
                return ServiceResult<ProductDto>.Forbidden("Bạn không có quyền đối với sản phẩm này");
            var category = await _categoryRepository.GetCategoryAsync(tenantId, createDto.CategoryId);
            if (!await _categoryRepository.CategoryExists(tenantId, createDto.CategoryId) || category == null)
                return ServiceResult<ProductDto>.Fail(400, "Category không tồn tại trong tenant này");
            var productCreationDataResult = ResolveProductCreationData(createDto);
            if (!productCreationDataResult.Success)
                return ServiceResult<ProductDto>.Fail(productCreationDataResult.StatusCode, productCreationDataResult.Message ?? "Dữ liệu SKU không hợp lệ");
            var productCreationData = productCreationDataResult.Data;
            if (productCreationData == null)
                return ServiceResult<ProductDto>.Fail(500, "Không thể xử lý dữ liệu sản phẩm");
            var product = createDto.ToProductFromCreateDto(tenantId, productCreationData.Attributes, productCreationData.Skus);

            await using var transaction = await _context.Database.BeginTransactionAsync();
            var createdProduct = await _productRepository.CreateProductAsync(product);
            await transaction.CommitAsync();

            return ServiceResult<ProductDto>.Created(createdProduct.ToProductDto());
        }

        public async Task<ServiceResult<ProductDto>> UpdateProductAsync(Guid tenantId, Guid platformUserId, Guid productId, UpdateProductRequestDto updateDto)
        {
            if (!await _tenantRepository.IsTenantOwner(tenantId, platformUserId))
                return ServiceResult<ProductDto>.Forbidden("Bạn không có quyền đối với sản phẩm này");
            var product = await _productRepository.GetProductAsync(tenantId, productId);
            if (!await _productRepository.ProductExists(tenantId, productId) || product == null)
                return ServiceResult<ProductDto>.Fail(404, "không tìm thấy sản phẩm!");
            if (updateDto.CategoryId.HasValue && !await _categoryRepository.CategoryExists(tenantId, updateDto.CategoryId.Value))
                return ServiceResult<ProductDto>.Fail(400, "Category không tồn tại trong tenant này");

            await using var transaction = await _context.Database.BeginTransactionAsync();

            if (updateDto.Skus != null)
                return ServiceResult<ProductDto>.Fail(400, "Không được replace toàn bộ SKU trong endpoint cập nhật sản phẩm. Hãy dùng endpoint tạo/sửa/xóa SKU riêng để tránh mất cart, review, order history.");

            updateDto.ToProductFromUpdateDto(product);
            var updatedProduct = await _productRepository.UpdateProductAsync(product);

            await transaction.CommitAsync();
            return ServiceResult<ProductDto>.Ok(updatedProduct.ToProductDto());
        }
        public async Task<ServiceResult<object>> DeleteProductAsync(Guid tenantId, Guid platformUserId, Guid productId)
        {
            if (!await _tenantRepository.IsTenantOwner(tenantId, platformUserId))
                return ServiceResult<object>.Forbidden("Bạn không có quyền đối với sản phẩm này");
            var product = await _productRepository.GetProductAsync(tenantId, productId);
            if (product == null)
                return ServiceResult<object>.Fail(404, "không tìm thấy sản phẩm!");

            await using var transaction = await _context.Database.BeginTransactionAsync();

            var removeSkusResult = await RemoveProductSkusAsync(tenantId, product.ProductSkus);
            if (!removeSkusResult.Success)
                return ServiceResult<object>.Fail(removeSkusResult.StatusCode, removeSkusResult.Message ?? "Không thể xóa sản phẩm");

            await _productRepository.DeleteProductAsync(tenantId, productId);
            await transaction.CommitAsync();
            return ServiceResult<object>.Ok(new { message = "Xóa sản phẩm thành công!" });
        }

        public async Task<ServiceResult<IEnumerable<ProductSkuDto>>> GetSkusAsync(Guid tenantId, Guid productId)
        {
            if (!await _productRepository.ProductExists(tenantId, productId))
                return ServiceResult<IEnumerable<ProductSkuDto>>.Fail(404, "Không tìm thấy sản phẩm!");
            var skus = await _productSkuRepository.GetProductSkusByProductAsync(tenantId, productId) ?? [];
            return ServiceResult<IEnumerable<ProductSkuDto>>.Ok(skus.Select(s => s.ToProductSkuDto()));
        }

        public async Task<ServiceResult<ProductSkuDto>> CreateSkuAsync(Guid tenantId, Guid platformUserId, Guid productId, CreateProductSkuRequestDto createDto)
        {
            if (!await _tenantRepository.IsTenantOwner(tenantId, platformUserId))
                return ServiceResult<ProductSkuDto>.Forbidden("Bạn không có quyền đối với sản phẩm này");
            if (!await _productRepository.ProductExists(tenantId, productId))
                return ServiceResult<ProductSkuDto>.Fail(404, "Không tìm thấy sản phẩm!");
            var sku = createDto.ToProductSkuFromCreateDto(productId);
            var createdSku = await _productSkuRepository.CreateProductSkuAsync(sku);
            return ServiceResult<ProductSkuDto>.Ok(createdSku.ToProductSkuDto());
        }

        public async Task<ServiceResult<ProductSkuDto>> UpdateSkuAsync(Guid tenantId, Guid platformUserId, Guid productId, Guid skuId, UpdateProductSkuRequestDto updateDto)
        {
            if (!await _tenantRepository.IsTenantOwner(tenantId, platformUserId))
                return ServiceResult<ProductSkuDto>.Forbidden("Bạn không có quyền đối với sản phẩm này");
            if (!await _productRepository.ProductExists(tenantId, productId))
                return ServiceResult<ProductSkuDto>.Fail(404, "Không tìm thấy sản phẩm!");
            var sku = await _productSkuRepository.GetProductSkusAsync(tenantId, skuId);
            if (sku == null || sku.ProductId != productId)
                return ServiceResult<ProductSkuDto>.Fail(404, "Không tìm thấy SKU!");
            updateDto.ToProductSkuFromUpdateDto(sku);
            var updatedSku = await _productSkuRepository.UpdateProductSkuAsync(sku);
            return ServiceResult<ProductSkuDto>.Ok(updatedSku.ToProductSkuDto());
        }

        public async Task<ServiceResult<object>> DeleteSkuAsync(Guid tenantId, Guid platformUserId, Guid productId, Guid skuId)
        {
            if (!await _tenantRepository.IsTenantOwner(tenantId, platformUserId))
                return ServiceResult<object>.Forbidden("Bạn không có quyền đối với sản phẩm này");
            if (!await _productRepository.ProductExists(tenantId, productId))
                return ServiceResult<object>.Fail(404, "Không tìm thấy sản phẩm!");
            var sku = await _productSkuRepository.GetProductSkusAsync(tenantId, skuId);
            if (sku == null || sku.ProductId != productId)
                return ServiceResult<object>.Fail(404, "Không tìm thấy SKU!");

            var removeSkusResult = await RemoveProductSkusAsync(tenantId, new[] { sku });
            if (!removeSkusResult.Success)
                return ServiceResult<object>.Fail(removeSkusResult.StatusCode, removeSkusResult.Message ?? "Không thể xóa SKU");

            return ServiceResult<object>.Ok(new { message = "Xóa SKU thành công!" });
        }
    }
}