using FluxifyAPI.DTOs.Product;
using FluxifyAPI.DTOs.ProductSku;
using FluxifyAPI.Helpers;
using FluxifyAPI.Repository.Interfaces;
using FluxifyAPI.Mapper;
using FluxifyAPI.Services.Interfaces;
using FluxifyAPI.Services.Common;
using Microsoft.EntityFrameworkCore;

namespace FluxifyAPI.Services.Implementations
{
    public class ProductService : IProductService
    {
        private const int MaxAutoGeneratedSkuCount = 500;

        private sealed class ProductCreationData
        {
            public Dictionary<string, List<string>>? Attributes { get; init; }
            public List<CreateProductSkuRequestDto> Skus { get; init; } = new();
        }

        private readonly IProductRepository _productRepository;
        private readonly IProductSkuRepository _productSkuRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly ITenantRepository _tenantRepository;

        public ProductService(
            IProductRepository productRepository,
            IProductSkuRepository productSkuRepository,
            ICategoryRepository categoryRepository,
            ITenantRepository tenantRepository)
        {
            _productRepository = productRepository;
            _productSkuRepository = productSkuRepository;
            _categoryRepository = categoryRepository;
            _tenantRepository = tenantRepository;
        }

        private static Dictionary<string, List<string>>? NormalizeProductAttributes(Dictionary<string, List<string>>? attributes)
        {
            if (attributes == null || attributes.Count == 0)
                return null;

            var normalized = new Dictionary<string, List<string>>(StringComparer.OrdinalIgnoreCase);

            foreach (var entry in attributes)
            {
                if (string.IsNullOrWhiteSpace(entry.Key))
                    continue;

                var normalizedKey = entry.Key.Trim();
                var normalizedValues = (entry.Value ?? new List<string>())
                    .Where(v => !string.IsNullOrWhiteSpace(v))
                    .Select(v => v.Trim())
                    .Distinct(StringComparer.OrdinalIgnoreCase)
                    .ToList();

                normalized[normalizedKey] = normalizedValues;
            }

            return normalized.Count == 0 ? null : normalized;
        }

        private static Dictionary<string, string> NormalizeSkuAttributes(Dictionary<string, string>? attributes)
        {
            if (attributes == null || attributes.Count == 0)
                return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

            var normalized = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            foreach (var entry in attributes)
            {
                if (string.IsNullOrWhiteSpace(entry.Key) || string.IsNullOrWhiteSpace(entry.Value))
                    continue;

                normalized[entry.Key.Trim()] = entry.Value.Trim();
            }

            return normalized;
        }

        private static string BuildSkuAttributeKey(IReadOnlyDictionary<string, string> attributes)
        {
            return string.Join("|", attributes
                .OrderBy(entry => entry.Key, StringComparer.OrdinalIgnoreCase)
                .Select(entry => $"{entry.Key.ToLowerInvariant()}={entry.Value.ToLowerInvariant()}"));
        }

        private static List<Dictionary<string, string>> BuildAttributeCombinations(Dictionary<string, List<string>> productAttributes)
        {
            var combinations = new List<Dictionary<string, string>>
            {
                new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            };

            foreach (var attributeGroup in productAttributes)
            {
                var nextCombinations = new List<Dictionary<string, string>>();

                foreach (var existingCombination in combinations)
                {
                    foreach (var value in attributeGroup.Value)
                    {
                        var nextCombination = new Dictionary<string, string>(existingCombination, StringComparer.OrdinalIgnoreCase)
                        {
                            [attributeGroup.Key] = value
                        };

                        nextCombinations.Add(nextCombination);
                    }
                }

                combinations = nextCombinations;
            }

            return combinations;
        }

        private static ServiceResult<ProductCreationData> ResolveProductCreationData(CreateProductRequestDto createDto)
        {
            var normalizedProductAttributes = NormalizeProductAttributes(createDto.Attributes);
            if (normalizedProductAttributes == null)
            {
                return ServiceResult<ProductCreationData>.Ok(new ProductCreationData
                {
                    Attributes = null,
                    Skus = createDto.Skus ?? new List<CreateProductSkuRequestDto>()
                });
            }

            if (normalizedProductAttributes.Any(attribute => attribute.Value.Count == 0))
                return ServiceResult<ProductCreationData>.Fail(400, "Mỗi nhóm thuộc tính phải có ít nhất một giá trị");

            long skuCount = 1;
            foreach (var values in normalizedProductAttributes.Values)
            {
                skuCount *= values.Count;
                if (skuCount > MaxAutoGeneratedSkuCount)
                {
                    return ServiceResult<ProductCreationData>.Fail(
                        400,
                        $"Số lượng SKU tự động vượt quá giới hạn {MaxAutoGeneratedSkuCount}");
                }
            }

            var providedSkus = createDto.Skus ?? new List<CreateProductSkuRequestDto>();
            var providedSkuByKey = new Dictionary<string, CreateProductSkuRequestDto>(StringComparer.OrdinalIgnoreCase);
            CreateProductSkuRequestDto? defaultSkuTemplate = null;

            foreach (var providedSku in providedSkus)
            {
                var normalizedSkuAttributes = NormalizeSkuAttributes(providedSku.Attributes);
                if (normalizedSkuAttributes.Count == 0)
                {
                    defaultSkuTemplate ??= providedSku;
                    continue;
                }

                foreach (var skuAttribute in normalizedSkuAttributes)
                {
                    if (!normalizedProductAttributes.TryGetValue(skuAttribute.Key, out var allowedValues) ||
                        !allowedValues.Contains(skuAttribute.Value, StringComparer.OrdinalIgnoreCase))
                    {
                        return ServiceResult<ProductCreationData>.Fail(
                            400,
                            $"SKU attributes không hợp lệ: {skuAttribute.Key}={skuAttribute.Value}");
                    }
                }

                var skuKey = BuildSkuAttributeKey(normalizedSkuAttributes);
                if (!providedSkuByKey.TryAdd(skuKey, providedSku))
                    return ServiceResult<ProductCreationData>.Fail(400, "Có SKU bị trùng tổ hợp attributes");
            }

            var combinations = BuildAttributeCombinations(normalizedProductAttributes);
            var autoGeneratedSkus = new List<CreateProductSkuRequestDto>(combinations.Count);

            foreach (var combination in combinations)
            {
                var combinationKey = BuildSkuAttributeKey(combination);

                if (providedSkuByKey.TryGetValue(combinationKey, out var providedSku))
                {
                    autoGeneratedSkus.Add(new CreateProductSkuRequestDto
                    {
                        Price = providedSku.Price,
                        Stock = providedSku.Stock,
                        imgUrl = providedSku.imgUrl,
                        Attributes = combination
                    });
                    continue;
                }

                if (defaultSkuTemplate != null)
                {
                    autoGeneratedSkus.Add(new CreateProductSkuRequestDto
                    {
                        Price = defaultSkuTemplate.Price,
                        Stock = defaultSkuTemplate.Stock,
                        imgUrl = defaultSkuTemplate.imgUrl,
                        Attributes = combination
                    });
                    continue;
                }

                autoGeneratedSkus.Add(new CreateProductSkuRequestDto
                {
                    Price = 0,
                    Stock = 0,
                    imgUrl = string.Empty,
                    Attributes = combination
                });
            }

            return ServiceResult<ProductCreationData>.Ok(new ProductCreationData
            {
                Attributes = normalizedProductAttributes,
                Skus = autoGeneratedSkus
            });
        }

        public async Task<ServiceResult<IEnumerable<ProductDto>>> GetProductsAsync(Guid tenantId, QueryProduct query)
        {
            var productQuery = _productRepository.GetProductsByTenant(tenantId);

            var searchTerm = query.SearchTerm;
            if (!string.IsNullOrEmpty(searchTerm))
                productQuery = productQuery.Where(p =>
                    p.Name.Contains(searchTerm) ||
                    (p.Description != null && p.Description.Contains(searchTerm)));
            if (!string.IsNullOrWhiteSpace(query.Name))
                productQuery = productQuery.Where(p => p.Name.Contains(query.Name.Trim()));
            if (query.CategoryId.HasValue)
                productQuery = productQuery.Where(p => p.CategoryId == query.CategoryId.Value);
            if (query.HasAttributes.HasValue)
                productQuery = query.HasAttributes.Value
                    ? productQuery.Where(p => p.AttributesJson != null && p.AttributesJson != string.Empty)
                    : productQuery.Where(p => p.AttributesJson == null || p.AttributesJson == string.Empty);

            var isDescending = string.Equals(query.SortDirection, "desc", StringComparison.OrdinalIgnoreCase);
            switch (query.SortBy)
            {
                case "name":
                    productQuery = isDescending ? productQuery.OrderByDescending(p => p.Name) : productQuery.OrderBy(p => p.Name);
                    break;
                case "categoryid":
                case "category_id":
                    productQuery = isDescending ? productQuery.OrderByDescending(p => p.CategoryId) : productQuery.OrderBy(p => p.CategoryId);
                    break;
                case "id":
                    productQuery = isDescending ? productQuery.OrderByDescending(p => p.Id) : productQuery.OrderBy(p => p.Id);
                    break;
                default:
                    productQuery = productQuery.OrderBy(p => p.Id);
                    break;
            }

            var skipNumber = (query.Page - 1) * query.PageSize;

            var products = await productQuery.Skip(skipNumber).Take(query.PageSize).ToListAsync();
            return ServiceResult<IEnumerable<ProductDto>>.Ok(products.Select(p => p.ToProductDto()));
        }

        public async Task<ServiceResult<ProductDto>> GetProductAsync(Guid tenantId, Guid id)
        {
            var product = await _productRepository.GetProductAsync(tenantId, id);
            if (product == null)
                return ServiceResult<ProductDto>.Fail(404, "Không tìm thấy sản phẩm");

            return ServiceResult<ProductDto>.Ok(product.ToProductDto());
        }

        public async Task<ServiceResult<ProductDto>> CreateProductAsync(Guid tenantId, Guid platformUserId, CreateProductRequestDto createDto)
        {
            if (!await _tenantRepository.IsTenantOwner(tenantId, platformUserId))
                return ServiceResult<ProductDto>.Forbidden("Bạn không có quyền đối với sản phẩm này");

            var category = await _categoryRepository.GetCategoryAsync(tenantId, createDto.CategoryId);
            if (category == null)
                return ServiceResult<ProductDto>.Fail(400, "Category không tồn tại trong tenant này");

            var productCreationDataResult = ResolveProductCreationData(createDto);
            if (!productCreationDataResult.Success)
                return ServiceResult<ProductDto>.Fail(productCreationDataResult.StatusCode, productCreationDataResult.Message ?? "Dữ liệu SKU không hợp lệ");

            var productCreationData = productCreationDataResult.Data;
            if (productCreationData == null)
                return ServiceResult<ProductDto>.Fail(500, "Không thể xử lý dữ liệu sản phẩm");

            var product = createDto.ToProductFromCreateDto(tenantId, productCreationData.Attributes, productCreationData.Skus);
            var createdProduct = await _productRepository.CreateProductAsync(product);

            return ServiceResult<ProductDto>.Ok(createdProduct.ToProductDto());
        }

        public async Task<ServiceResult<ProductDto>> UpdateProductAsync(Guid tenantId, Guid platformUserId, Guid productId, UpdateProductRequestDto updateDto)
        {
            if (!await _tenantRepository.IsTenantOwner(tenantId, platformUserId))
                return ServiceResult<ProductDto>.Forbidden("Bạn không có quyền đối với sản phẩm này");
            var product = await _productRepository.GetProductAsync(tenantId, productId);
            if (product == null)
                return ServiceResult<ProductDto>.Fail(404, "không tìm thấy sản phẩm!");
            if (updateDto.CategoryId.HasValue && !await _categoryRepository.IsCategoryExists(tenantId, updateDto.CategoryId.Value))
                return ServiceResult<ProductDto>.Fail(400, "Category không tồn tại trong tenant này");
            updateDto.ToProductFromUpdateDto(product);
            var updatedProduct = await _productRepository.UpdateProductAsync(product);
            return ServiceResult<ProductDto>.Ok(updatedProduct.ToProductDto());
        }

        public async Task<ServiceResult<object>> DeleteProductAsync(Guid tenantId, Guid platformUserId, Guid productId)
        {
            try
            {
                if (!await _tenantRepository.IsTenantOwner(tenantId, platformUserId))
                    return ServiceResult<object>.Forbidden("Bạn không có quyền đối với sản phẩm này");
                var product = await _productRepository.DeleteProductAsync(tenantId, productId);
                if (product == null)
                    return ServiceResult<object>.Fail(404, "không tìm thấy sản phẩm!");
                return ServiceResult<object>.Ok(new { message = "Xoa thanh cong!" });
            }
            catch (DbUpdateException)
            {
                return ServiceResult<object>.Fail(400, "Không thể xóa sản phẩm vì SKU đang được tham chiếu trong giỏ hàng hoặc đơn hàng");
            }
        }

        public async Task<ServiceResult<IEnumerable<ProductSkuDto>>> GetSkusAsync(Guid tenantId, Guid productId)
        {
            if (!await _productRepository.IsProductExists(tenantId, productId))
                return ServiceResult<IEnumerable<ProductSkuDto>>.Fail(404, "Không tìm thấy sản phẩm!");
            var skus = await _productSkuRepository.GetProductSkusByProductAsync(tenantId, productId) ?? [];
            return ServiceResult<IEnumerable<ProductSkuDto>>.Ok(skus.Select(s => s.ToProductSkuDto()));
        }

        public async Task<ServiceResult<ProductSkuDto>> CreateSkuAsync(Guid tenantId, Guid platformUserId, Guid productId, CreateProductSkuRequestDto createDto)
        {
            if (!await _tenantRepository.IsTenantOwner(tenantId, platformUserId))
                return ServiceResult<ProductSkuDto>.Forbidden("Bạn không có quyền đối với sản phẩm này");
            if (!await _productRepository.IsProductExists(tenantId, productId))
                return ServiceResult<ProductSkuDto>.Fail(404, "Không tìm thấy sản phẩm!");
            var sku = createDto.ToProductSkuFromCreateDto(productId);
            var createdSku = await _productSkuRepository.CreateProductSkuAsync(sku);
            return ServiceResult<ProductSkuDto>.Ok(createdSku.ToProductSkuDto());
        }

        public async Task<ServiceResult<ProductSkuDto>> UpdateSkuAsync(Guid tenantId, Guid platformUserId, Guid productId, Guid skuId, UpdateProductSkuRequestDto updateDto)
        {
            if (!await _tenantRepository.IsTenantOwner(tenantId, platformUserId))
                return ServiceResult<ProductSkuDto>.Forbidden("Bạn không có quyền đối với sản phẩm này");
            if (!await _productRepository.IsProductExists(tenantId, productId))
                return ServiceResult<ProductSkuDto>.Fail(404, "Không tìm thấy sản phẩm!");
            var sku = await _productSkuRepository.GetProductSkusAsync(tenantId, skuId);
            if (sku == null || sku.ProductId != productId)
                return ServiceResult<ProductSkuDto>.Fail(404, "Không tìm thấy SKU!");
            updateDto.ToProductSkuFromUpdateDto(sku);
            var updatedSku = await _productSkuRepository.UpdateProductSkuAsync(sku);
            return ServiceResult<ProductSkuDto>.Ok(updatedSku.ToProductSkuDto());
        }

        public async Task<ServiceResult<object>> DeleteSkuAsync(Guid tenantId, Guid platformUserId, Guid productId, Guid skuId)
        {
            if (!await _tenantRepository.IsTenantOwner(tenantId, platformUserId))
                return ServiceResult<object>.Forbidden("Bạn không có quyền đối với sản phẩm này");
            if (!await _productRepository.IsProductExists(tenantId, productId))
                return ServiceResult<object>.Fail(404, "Không tìm thấy sản phẩm!");
            var sku = await _productSkuRepository.GetProductSkusAsync(tenantId, skuId);
            if (sku == null || sku.ProductId != productId)
                return ServiceResult<object>.Fail(404, "Không tìm thấy SKU!");

            try
            {
                await _productSkuRepository.DeleteProductSkuAsync(tenantId, skuId);
                return ServiceResult<object>.Ok(new { message = "Xóa SKU thành công!" });
            }
            catch (DbUpdateException)
            {
                return ServiceResult<object>.Fail(400, "Không thể xóa SKU vì đang được tham chiếu trong giỏ hàng hoặc đơn hàng");
            }
        }
    }
}




